version: '3.3'

services:
  app-web:
    image: oliverjpr/barcamp-from-docker
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://base-datos-app-web:3306/barcamp
    networks:
      - red-app
    depends_on:
      - base-datos-app-web
  app-web2:
    image: oliverjpr/barcamp-from-docker
    ports:
      - 8081:8081
    environment:
      - spring.datasource.url=jdbc:mysql://base-datos-app-web:3306/barcamp
    networks:
      - red-app
    depends_on:
      - base-datos-app-web
  app-web3:
    image: oliverjpr/barcamp-from-docker
    ports:
      - 8082:8082
    environment:
      - spring.datasource.url=jdbc:mysql://base-datos-app-web:3306/barcamp
    networks:
      - red-app
    depends_on:
      - base-datos-app-web
  ha-proxy:
    networks:
      - red-app
    depends_on:
      - app-web
      - app-web2
      - app-web3
    image: haproxy:2.0.2
    volumes:
    - /opt/ci-with-haproxy/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 81:20


  base-datos-app-web:
    image: library/mysql:5.7.16
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=root
      - MYSQL_DATABASE=barcamp
    volumes:
      - ~/datadir_mysql:/var/lib/mysql
    networks:
      - red-app
networks:
  red-app:
